### ISSUE TITLE
Add a helm chart for kubernetes deployment

### ISSUE THREAD

**Issue by stan-dot** [ChannelFinder/ChannelFinderService#162]

**Comment by stan-dot** [comment]
deployent needs to reference an existing image 

```yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "channelfinder.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "channelfinder.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "channelfinder.name" . }}
    spec:
      containers:
        - name: channelfinder
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: ELASTICSEARCH_NETWORK_HOST
              value: "elasticsearch-cf"
          command:
            - /bin/bash
            - -c
            - |
              until curl --silent --fail http://elasticsearch-cf:9200/_cluster/health; do
                echo 'Waiting for Elasticsearch';
                sleep 1;
              done;
              java -jar /channelfinder/ChannelFinder-*.jar
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: es-data


```

**Comment by stan-dot** [comment]
all existing images seem old
https://hub.docker.com/search?q=channelfinder

**Comment by stan-dot** [comment]
might choose to push to the DLS registry

https://dev-portal.diamond.ac.uk/guide/kubernetes/tutorials/containers/

**Comment by stan-dot** [comment]
with this 

```yaml

image:
  repository: channelfinder
  tag: "latest"
  pullPolicy: IfNotPresent
  
```


https://confluence.diamond.ac.uk/display/CLOUD/Container+Registry
